#!/bin/sh
# Guest-side helper for tests/vm/validate-netns.sh. Runs ON B (the proxy box).
#
#   fw-up <server_ip> <server_port>   model the testers' firewall (default DROP)
#   fw-up-ufw <srv> <port> <subnet>   the same box via REAL ufw (CTRL=<iface> opt)
#   fw-ufw-install                    apt-get install ufw (ships disabled)
#   fw-dump                           `iptables -S`, as the preflight reads it
#   l4-probe                          yes/no: do FIB rules take L4 selectors?
#   fw-down                           restore the ruleset saved by either fw-up
#   fw-hash                           stable digest of the live ruleset (no counters)
#   fw-show                           print the live ruleset
#   mm-start <plain|netns> <cfg>      launch mymitm (netns => inside 'mitm')
#   mm-stop                           SIGTERM it and wait for RAII teardown
#   mm-log                            print its log
set -u

LOG=/var/log/mm.log
PIDF=/var/run/mm.testkit.pid
FWSAVE=/root/fw.pre-mymitm
FWGUARD=/run/mm.fwguard    # watchdog cancel flag (see fw-up)

# The live ruleset, normalized so its digest tracks RULES and not traffic. Two
# things vary independently of any rule change:
#   - the "# Generated by ..." timestamp comment,
#   - the built-in chain policy counters. `iptables-save` prints these as
#     ":INPUT ACCEPT [34:4611]" even WITHOUT -c, so every packet through the box
#     changes them; hashing them raw makes "the firewall was modified" fire on
#     nothing more than a ping.
# Restricted to the three tables the test cares about: `iptables-save` emits a
# *table section only for tables whose MODULE is loaded, so a module appearing
# mid-run (the iproute plane loading nat/mangle, a *raw showing up) adds a whole
# section and the digest moves with no rule change -- reported as "the firewall
# CHANGED". Asking for each table by name loads and prints all three every time.
#
# One table PER CALL: `iptables-save -t filter -t nat -t mangle` exits 0 but honors
# only the LAST -t, so it silently dumps mangle alone. (Caught by the *filter floor
# in fw-hash, which is why that floor exists.)
fw_norm() {
  _d=""
  for _t in filter nat mangle; do
    _o="$(iptables-save -t "$_t")" || return 1
    _d="$_d$_o
"
  done
  printf '%s' "$_d" | grep -v '^#' | sed 's/\[[0-9]*:[0-9]*\]/[0:0]/g'
}

cmd="${1:-}"; shift 2>/dev/null || true

case "$cmd" in
# ---------------------------------------------------------------------------
# The testers' firewall, modelled: a forwarding box that permits exactly one
# forwarded service, ssh + openvpn inbound, ntp + logs outbound, and drops
# everything else. This is what breaks interception -- the client's SYN now
# arrives at INPUT and the proxy's upstream SYN leaves via OUTPUT, and neither
# chain has a rule for them.
# ---------------------------------------------------------------------------
fw-up)
  SERVER="${1:?server ip}"; PORT="${2:?server port}"
  iptables-save > "$FWSAVE" || exit 1

  # Watchdog: restore the saved ruleset in ~15 min unless fw-down cancels it by
  # removing the flag file. A firewall mistake here must never permanently lock
  # the box out -- which it did on the first attempt at this test.
  touch "$FWGUARD"
  setsid sh -c 'i=0; while [ $i -lt 180 ]; do [ -f '"$FWGUARD"' ] || exit 0; sleep 5; i=$((i+1)); done; iptables-restore < '"$FWSAVE" \
    >/dev/null 2>&1 </dev/null &

  # Applied as ONE atomic iptables-restore: no window in which the policies are
  # DROP but the accept rules are not yet in place.
  #
  # NOTE the stateless ssh pair (--dport 22 in, --sport 22 out). The obvious
  # version -- rely on the ESTABLISHED rule for the reply direction -- locks out
  # the very ssh session that applies the profile: conntrack only starts
  # tracking that connection mid-stream, so its packets are not ESTABLISHED and
  # the OUTPUT DROP policy silently eats the replies. New sessions are fine,
  # which makes it a confusing hang. Two stateless rules make ssh immune.
  # They cannot affect the result: the proxy's legs are INPUT to
  # <local_addr>:8443 and OUTPUT to <server>:<port>, neither of which is port 22.
  iptables-restore <<EOF
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT DROP [0:0]
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A INPUT -p tcp --dport 22 -j ACCEPT
-A OUTPUT -p tcp --sport 22 -j ACCEPT
-A INPUT -p udp --dport 1194 -j ACCEPT
-A FORWARD -p tcp -d $SERVER --dport $PORT -j ACCEPT
-A OUTPUT -p udp --dport 123 -j ACCEPT
-A OUTPUT -p tcp --dport 6514 -j ACCEPT
COMMIT
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
*mangle
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
EOF
  rc=$?
  if [ $rc -ne 0 ]; then
    echo "fw-up: iptables-restore failed ($rc); rolling back" >&2
    iptables-restore < "$FWSAVE"; rm -f "$FWGUARD"; exit 1
  fi
  # Verify the profile really took, so a silent partial apply can't be mistaken
  # for a valid "the firewall blocks it" result.
  iptables -S | grep -q "^-P INPUT DROP"   || { echo "fw-up: INPUT policy is not DROP" >&2; exit 1; }
  iptables -S | grep -q "^-P OUTPUT DROP"  || { echo "fw-up: OUTPUT policy is not DROP" >&2; exit 1; }
  iptables -S | grep -q "^-P FORWARD DROP" || { echo "fw-up: FORWARD policy is not DROP" >&2; exit 1; }
  iptables -S | grep -q -- "-A FORWARD -d $SERVER/32 -p tcp -m tcp --dport $PORT -j ACCEPT" \
    || { echo "fw-up: the permitted-forward rule is missing" >&2; iptables -S FORWARD >&2; exit 1; }
  echo "fw-up: default-DROP profile applied (forward -> $SERVER:$PORT only); saved previous to $FWSAVE"
  ;;

# ---------------------------------------------------------------------------
# The same box, but expressed through REAL ufw instead of a hand-written
# ruleset -- because that is what the testers run, and because a fixture of
# what ufw "probably" emits is not evidence. Applies verbatim:
#
#   ufw allow in on <ctrl> to <ctrl_ip> port 22 proto tcp   (mgmt NIC == their eth1)
#   ufw allow in on <ctrl> to <ctrl_ip> port 1194 proto udp
#   ufw deny from <client_subnet>                           (their vpn_subnet)
#   ufw route allow from <client_subnet> to <server> port <port> proto tcp
#   ufw route allow from <client_subnet> to <server> port 3391 proto udp
#
# with default deny incoming / deny routed / allow outgoing, which are ufw's
# own defaults (DEFAULT_OUTPUT_POLICY is ACCEPT -- verified, not assumed).
# ---------------------------------------------------------------------------
fw-up-ufw)
  SERVER="${1:?server ip}"; PORT="${2:?server port}"; VPN="${3:?client subnet}"
  command -v ufw >/dev/null 2>&1 || { echo "fw-up-ufw: ufw not installed (run fw-ufw-install)" >&2; exit 1; }
  iptables-save > "$FWSAVE" || exit 1

  # Same watchdog as fw-up, plus `ufw disable` -- restoring the saved ruleset
  # alone would leave ufw believing it is still enabled and re-applying on boot.
  touch "$FWGUARD"
  setsid sh -c 'i=0; while [ $i -lt 180 ]; do [ -f '"$FWGUARD"' ] || exit 0; sleep 5; i=$((i+1)); done; ufw --force disable; iptables-restore < '"$FWSAVE" \
    >/dev/null 2>&1 </dev/null &

  # Start from a known state: reset backs up any existing user rules and
  # disables ufw, so this is repeatable across runs.
  ufw --force reset >/dev/null 2>&1

  # ssh FIRST and *statelessly*, before enabling. ufw's own INPUT path accepts
  # RELATED,ESTABLISHED (before.rules), but the ssh session carrying these very
  # commands has no conntrack entry yet on a box that had no conntrack rules --
  # exactly the mid-stream case that orphaned the session the first time this
  # test was attempted. A ufw user rule is a stateless ACCEPT, so it is immune.
  # Cannot affect the result: the proxy's legs are never port 22.
  ufw allow 22/tcp >/dev/null

  ufw default deny incoming  >/dev/null
  ufw default allow outgoing >/dev/null
  ufw default deny routed    >/dev/null

  # The tester box's rules. CTRL is the management NIC, standing in for eth1.
  if [ -n "${CTRL:-}" ]; then
    CTRL_IP="$(ip -4 -o addr show dev "$CTRL" 2>/dev/null | awk '{print $4}' | cut -d/ -f1)"
    [ -n "$CTRL_IP" ] && ufw allow in on "$CTRL" to "$CTRL_IP" port 22 proto tcp >/dev/null
    [ -n "$CTRL_IP" ] && ufw allow in on "$CTRL" to "$CTRL_IP" port 1194 proto udp >/dev/null
  fi
  ufw deny from "$VPN" >/dev/null
  ufw route allow from "$VPN" to "$SERVER" port "$PORT" proto tcp >/dev/null
  ufw route allow from "$VPN" to "$SERVER" port 3391 proto udp >/dev/null

  ufw --force enable >/dev/null 2>&1
  rc=$?
  if [ $rc -ne 0 ]; then
    echo "fw-up-ufw: ufw enable failed ($rc); rolling back" >&2
    ufw --force disable >/dev/null 2>&1; iptables-restore < "$FWSAVE"; rm -f "$FWGUARD"; exit 1
  fi

  # ufw does NOT manage ip_forward (its sysctl.conf sets accept_redirects,
  # icmp_* and log_martians only), so a router keeps whatever it had. Assert it,
  # since netns mode requires it and a silent 0 would look like a proxy bug.
  [ "$(cat /proc/sys/net/ipv4/ip_forward)" = 1 ] \
    || { echo "fw-up-ufw: ip_forward is 0 after enabling ufw" >&2; exit 1; }

  # Verify the profile really took: the permission must exist, in the chain we
  # expect, WITHOUT an -i/-o pin (that is the whole premise of the test).
  fwd="$(iptables -S ufw-user-forward 2>/dev/null)"
  echo "$fwd" | grep -q -- "-d $SERVER/32 .*--dport $PORT .*-j ACCEPT" \
    || { echo "fw-up-ufw: no ufw-user-forward permission for $SERVER:$PORT" >&2; echo "$fwd" >&2; exit 1; }
  echo "$fwd" | grep -- "--dport $PORT " | grep -qE ' -(i|o) ' \
    && { echo "fw-up-ufw: the permission is interface-pinned; this profile must not be" >&2; exit 1; }
  iptables -S ufw-user-input | grep -q -- "-s $VPN -j DROP" \
    || { echo "fw-up-ufw: the 'deny from $VPN' INPUT rule is missing" >&2; exit 1; }
  echo "fw-up-ufw: real ufw enabled (route allow $VPN -> $SERVER:$PORT tcp + 3391 udp); saved previous to $FWSAVE"
  ;;

fw-ufw-install)
  command -v ufw >/dev/null 2>&1 && { echo "fw-ufw-install: already present ($(ufw version 2>/dev/null | head -1))"; exit 0; }
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq >/dev/null 2>&1
  # ufw ships with ENABLED=no, so installing it does not firewall the box.
  apt-get install -y -qq --no-install-recommends ufw >/dev/null 2>&1 \
    || { echo "fw-ufw-install: apt-get install ufw failed" >&2; exit 1; }
  echo "fw-ufw-install: $(ufw version 2>/dev/null | head -1)"
  ;;

# The live ruleset as the preflight sees it, for diffing against the unit-test
# fixture in mymitm/src/netns.rs. `iptables -S` == exactly what preflight() reads.
fw-dump) iptables -S ;;

# Does this kernel + iproute2 accept L4 selectors on a routing rule (>= 4.17)?
# The harness needs to know whether to EXPECT UDP to the server to keep flowing,
# and this is the only honest way to find out.
#
# The product deliberately has no such probe: it must not add and delete a
# throwaway rule on a customer's box just to interrogate the kernel, so it attempts
# the scoped steer rule and falls back if that is rejected. This is a throwaway
# QEMU guest that the validator has already firewalled, so the same objection does
# not apply -- but keep the two in sync, since the harness's expectation is only
# meaningful if it predicts what the product will do.
# Both failure modes -- old kernel, old iproute2 -- look identical from here.
l4-probe)
  P="priority 30998 iif lo to 127.0.0.1 ipproto tcp dport 1 lookup 253"
  # shellcheck disable=SC2086
  if ip rule add $P 2>/dev/null; then
    # shellcheck disable=SC2086
    ip rule del $P 2>/dev/null
    echo yes
  else
    echo no
  fi
  ;;

fw-down)
  [ -f "$FWSAVE" ] || { echo "no saved ruleset at $FWSAVE" >&2; exit 1; }
  rm -f "$FWGUARD"                     # cancel the watchdog
  # Harmless when ufw was never enabled; required when it was, or it re-applies.
  command -v ufw >/dev/null 2>&1 && ufw --force disable >/dev/null 2>&1
  iptables-restore < "$FWSAVE" || exit 1
  echo "fw-down: ruleset restored from $FWSAVE"
  ;;

# A digest with a FLOOR. `iptables-save` failing, missing, or printing nothing
# would otherwise hash to the constant sha256 of the empty string, and every
# "firewall byte-for-byte unchanged" assertion would agree while measuring nothing.
fw-hash)
  d="$(fw_norm)" || { echo "fw-hash: iptables-save failed" >&2; exit 1; }
  echo "$d" | grep -q '^\*filter'     || { echo "fw-hash: refusing to hash a dump with no *filter table (got $(echo "$d" | grep -c .) lines)" >&2; exit 1; }
  echo "$d" | sha256sum | cut -d' ' -f1
  ;;
fw-show) fw_norm ;;

mm-start)
  MODE="${1:?plain|netns}"; CFG="${2:?config path}"
  : > "$LOG"
  case "$MODE" in
    plain) nohup setsid /opt/mymitm/mymitm --config "$CFG" >"$LOG" 2>&1 </dev/null & ;;
    netns) nohup setsid ip netns exec mitm /opt/mymitm/mymitm --config "$CFG" >"$LOG" 2>&1 </dev/null & ;;
    *) echo "mode must be plain|netns" >&2; exit 2;;
  esac
  echo $! > "$PIDF"
  echo "mm-start: $MODE pid $(cat "$PIDF") cfg $CFG"
  ;;

mm-stop)
  # SIGTERM so Drop runs (detach classifiers, restore sysctls, remove rules).
  pkill -TERM -f '/opt/mymitm/mymitm --config' 2>/dev/null
  i=0
  while [ $i -lt 40 ]; do
    pgrep -f '/opt/mymitm/mymitm --config' >/dev/null 2>&1 || break
    i=$((i + 1)); sleep 0.25
  done
  pkill -KILL -f '/opt/mymitm/mymitm --config' 2>/dev/null
  rm -f "$PIDF"
  echo "mm-stop: done"
  ;;

# "Print the log" must succeed when there is no log yet -- an absent log is an
# answer (nothing has run), not an error, and callers use this command's status to
# tell whether the testkit itself is working.
mm-log) cat "$LOG" 2>/dev/null || true ;;
mm-alive) pgrep -f '/opt/mymitm/mymitm --config' >/dev/null 2>&1 && echo yes || echo no ;;

*) echo "usage: $0 {fw-up|fw-up-ufw|fw-ufw-install|fw-down|fw-hash|fw-show|fw-dump|l4-probe|mm-start|mm-stop|mm-log|mm-alive} ..." >&2; exit 2;;
esac
