#!/bin/sh
# Guest-side helper for tests/vm/validate-netns.sh. Runs ON B (the proxy box).
#
#   fw-up <server_ip> <server_port>   model the testers' firewall (default DROP)
#   fw-down                           restore the ruleset saved by fw-up
#   fw-hash                           stable digest of the live ruleset (no counters)
#   fw-show                           print the live ruleset
#   mm-start <plain|netns> <cfg>      launch mymitm (netns => inside 'mitm')
#   mm-stop                           SIGTERM it and wait for RAII teardown
#   mm-log                            print its log
set -u

LOG=/var/log/mm.log
PIDF=/var/run/mm.testkit.pid
FWSAVE=/root/fw.pre-mymitm
FWGUARD=/run/mm.fwguard    # watchdog cancel flag (see fw-up)

# The live ruleset, normalized so its digest tracks RULES and not traffic. Two
# things vary independently of any rule change:
#   - the "# Generated by ..." timestamp comment,
#   - the built-in chain policy counters. `iptables-save` prints these as
#     ":INPUT ACCEPT [34:4611]" even WITHOUT -c, so every packet through the box
#     changes them; hashing them raw makes "the firewall was modified" fire on
#     nothing more than a ping.
fw_norm() { iptables-save | grep -v '^#' | sed 's/\[[0-9]*:[0-9]*\]/[0:0]/g'; }

cmd="${1:-}"; shift 2>/dev/null || true

case "$cmd" in
# ---------------------------------------------------------------------------
# The testers' firewall, modelled: a forwarding box that permits exactly one
# forwarded service, ssh + openvpn inbound, ntp + logs outbound, and drops
# everything else. This is what breaks interception -- the client's SYN now
# arrives at INPUT and the proxy's upstream SYN leaves via OUTPUT, and neither
# chain has a rule for them.
# ---------------------------------------------------------------------------
fw-up)
  SERVER="${1:?server ip}"; PORT="${2:?server port}"
  iptables-save > "$FWSAVE" || exit 1

  # Watchdog: restore the saved ruleset in ~15 min unless fw-down cancels it by
  # removing the flag file. A firewall mistake here must never permanently lock
  # the box out -- which it did on the first attempt at this test.
  touch "$FWGUARD"
  setsid sh -c 'i=0; while [ $i -lt 180 ]; do [ -f '"$FWGUARD"' ] || exit 0; sleep 5; i=$((i+1)); done; iptables-restore < '"$FWSAVE" \
    >/dev/null 2>&1 </dev/null &

  # Applied as ONE atomic iptables-restore: no window in which the policies are
  # DROP but the accept rules are not yet in place.
  #
  # NOTE the stateless ssh pair (--dport 22 in, --sport 22 out). The obvious
  # version -- rely on the ESTABLISHED rule for the reply direction -- locks out
  # the very ssh session that applies the profile: conntrack only starts
  # tracking that connection mid-stream, so its packets are not ESTABLISHED and
  # the OUTPUT DROP policy silently eats the replies. New sessions are fine,
  # which makes it a confusing hang. Two stateless rules make ssh immune.
  # They cannot affect the result: the proxy's legs are INPUT to
  # <local_addr>:8443 and OUTPUT to <server>:<port>, neither of which is port 22.
  iptables-restore <<EOF
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT DROP [0:0]
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A INPUT -p tcp --dport 22 -j ACCEPT
-A OUTPUT -p tcp --sport 22 -j ACCEPT
-A INPUT -p udp --dport 1194 -j ACCEPT
-A FORWARD -p tcp -d $SERVER --dport $PORT -j ACCEPT
-A OUTPUT -p udp --dport 123 -j ACCEPT
-A OUTPUT -p tcp --dport 6514 -j ACCEPT
COMMIT
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
*mangle
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
EOF
  rc=$?
  if [ $rc -ne 0 ]; then
    echo "fw-up: iptables-restore failed ($rc); rolling back" >&2
    iptables-restore < "$FWSAVE"; rm -f "$FWGUARD"; exit 1
  fi
  # Verify the profile really took, so a silent partial apply can't be mistaken
  # for a valid "the firewall blocks it" result.
  iptables -S | grep -q "^-P INPUT DROP"  || { echo "fw-up: INPUT policy is not DROP" >&2; exit 1; }
  iptables -S | grep -q "^-P OUTPUT DROP" || { echo "fw-up: OUTPUT policy is not DROP" >&2; exit 1; }
  iptables -S | grep -q -- "-A FORWARD -d $SERVER/32 -p tcp -m tcp --dport $PORT -j ACCEPT" \
    || { echo "fw-up: the permitted-forward rule is missing" >&2; iptables -S FORWARD >&2; exit 1; }
  echo "fw-up: default-DROP profile applied (forward -> $SERVER:$PORT only); saved previous to $FWSAVE"
  ;;

fw-down)
  [ -f "$FWSAVE" ] || { echo "no saved ruleset at $FWSAVE" >&2; exit 1; }
  rm -f "$FWGUARD"                     # cancel the watchdog
  iptables-restore < "$FWSAVE" || exit 1
  echo "fw-down: ruleset restored from $FWSAVE"
  ;;

fw-hash) fw_norm | sha256sum | cut -d' ' -f1 ;;
fw-show) fw_norm ;;

mm-start)
  MODE="${1:?plain|netns}"; CFG="${2:?config path}"
  : > "$LOG"
  case "$MODE" in
    plain) nohup setsid /opt/mymitm/mymitm --config "$CFG" >"$LOG" 2>&1 </dev/null & ;;
    netns) nohup setsid ip netns exec mitm /opt/mymitm/mymitm --config "$CFG" >"$LOG" 2>&1 </dev/null & ;;
    *) echo "mode must be plain|netns" >&2; exit 2;;
  esac
  echo $! > "$PIDF"
  echo "mm-start: $MODE pid $(cat "$PIDF") cfg $CFG"
  ;;

mm-stop)
  # SIGTERM so Drop runs (detach classifiers, restore sysctls, remove rules).
  pkill -TERM -f '/opt/mymitm/mymitm --config' 2>/dev/null
  i=0
  while [ $i -lt 40 ]; do
    pgrep -f '/opt/mymitm/mymitm --config' >/dev/null 2>&1 || break
    i=$((i + 1)); sleep 0.25
  done
  pkill -KILL -f '/opt/mymitm/mymitm --config' 2>/dev/null
  rm -f "$PIDF"
  echo "mm-stop: done"
  ;;

mm-log) cat "$LOG" 2>/dev/null ;;
mm-alive) pgrep -f '/opt/mymitm/mymitm --config' >/dev/null 2>&1 && echo yes || echo no ;;

*) echo "usage: $0 {fw-up|fw-down|fw-hash|fw-show|mm-start|mm-stop|mm-log|mm-alive} ..." >&2; exit 2;;
esac
